### ISSUE TITLE
Small problem with PHP8

### ISSUE THREAD

**Issue by scherhak** [SchwarzerIT/laravel-rules#1]
Hi!
laravel-rules are not able to use with PHP8
`- schwarzer/laravel-rules[1.0.0, ..., 1.1.0] require php ^7.4 -> your php version (8.0.2) does not satisfy that requirement.`

**Comment by AndreSchwarzer** [comment]
Thanks for your interest. i'll have a look.

**Comment by AndreSchwarzer** [comment]
Hi @scherhak,

your request has been resolved.

[Release 1.2.0](https://github.com/SchwarzerIT/laravel-rules/releases/tag/1.2.0) should now fit your needs.
